### ISSUE TITLE
`deadline` is set when user lands on page and not when they send the transaction

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#107]
It looks like the `deadline` (and `destinationDeadline`) for a tx is set when a user lands on the page. I would expect the `deadline` to be set when sending the transaction.

This is an issue for users who sit on the page or have the page open in another tab and come back to it later (just happened to me). If it has been too long, the source chain tx will fail. If it hasn't been too long but has been a while, there is a chance the dest chain tx will fail.

To reproduce:
* Send a transaction and record the `deadline` value from calldata
* Wait 1 or 2 min
* Send a transaction and observe that `deadline` value is exact same as first call a few min ago

**Comment by miguelmota** [comment]
No longer an issue. Closing.
