### ISSUE TITLE
Convert button is not disabled if user has insufficient funds

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#113]
The "Convert" page allows a user to attempt an AMM swap even if they do not have enough input token. I would expect the "Convert" button to be disabled if the user does not have enough input funds to swap.

To reproduce:
* Go to "Convert" page and attempt to swap an amount greater than your current balance

![Screen Shot 2021-07-12 at 1 01 56 PM](https://user-images.githubusercontent.com/9441295/125348641-5716e700-e311-11eb-983e-1559c06a85ea.png)

**Comment by miguelmota** [comment]
![Peek 2021-08-10 11-01](https://user-images.githubusercontent.com/168240/128911339-fa2c3563-9c70-47e8-957c-575c666d9e83.gif)

No longer an issue. Closing.
