### ISSUE TITLE
Add "exports" field to support Node.js ESM in SDK

### ISSUE THREAD

**Issue by talentlessguy** [hop-protocol/hop#117]
Since Node 10 gone EOL and all LTS now support pure ESM, it would be cool if the SDK had "exports" declaration to support Node.js ESM imports, I mean this:

```js
import { Hop } from '@hop-protocol/sdk'
```

In order to be able to do that, the package should have an "exports" field defined like this:

```json
"exports": {
  "import": "./dist/index.js",
  "require": "./dist/index.cjs"
}
```

More resources regarding ESM:

- https://nodejs.org/api/packages.html#packages_exports
- https://2ality.com/2019/10/hybrid-npm-packages.html
- https://2ality.com/2021/06/typescript-esm-nodejs.html

**Comment by miguelmota** [comment]
Closing issue as stale but happy to review/accept any pull requests
