### ISSUE TITLE
No UI update after adding liquidity

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#118]
When adding liquidity, there is no clear indication that the addition has been completed. The "Your position" dropdown does not appear unless the page is refreshed.

I would expect the "Your position" dropdown to show after adding liquidity but before refreshing.

https://user-images.githubusercontent.com/9441295/126526003-79a7baca-b011-41c3-a5e7-3b095d35c522.mp4

**Comment by miguelmota** [comment]
I verified it's no longer an issue. Closing.
