### ISSUE TITLE
LP position does not show on Stake page until refresh

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#119]
When landing on the Stake page, the LP position does not show unless the page is refreshed.

I would expect the page to read the user's balance upon landing on the Stake page, not refresh.

https://user-images.githubusercontent.com/9441295/126526354-4a54f499-b485-4235-8e9f-12fd1134ef9b.mp4

**Comment by miguelmota** [comment]
No longer an issue. Closing.
