### ISSUE TITLE
"Insufficient balance" is shown after completion of a max stake

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#121]
When staking, a user is shown an "insufficient balance" warning when the stake transaction is completed. I _believe_ this is because we do not 0 out the input box.

I would expect the error to not show up after staking max.

https://user-images.githubusercontent.com/9441295/126526832-8b77eeb2-6149-4e36-9ae7-0943266f0c50.mp4

**Comment by miguelmota** [comment]
Closed by https://github.com/hop-protocol/hop/commit/502204ada598e0b94ff9473825022fa2e3d2d229
