### ISSUE TITLE
Use the MM network switching modal for mainnet

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#130]
Use the MM network switching modal when a user is switching to mainnet. I believe this may not have been possible before, but it looks like GSafe now does it.

<img width="463" alt="Screen Shot 2021-08-02 at 6 54 51 PM" src="https://user-images.githubusercontent.com/9441295/127945344-3c87e9c9-23bc-4b3c-9d92-c8bca7b63ab1.png">

**Comment by miguelmota** [comment]
![Peek 2021-08-10 11-11](https://user-images.githubusercontent.com/168240/128912845-288bb551-06fe-46af-9203-1415190781e3.gif)

Closed by https://github.com/hop-protocol/hop/commit/0eeeb1bde1309ead354d91838ebbd72fd4ec3e79
