### ISSUE TITLE
question: usage of window.fetch instead of node fetch

### ISSUE THREAD

**Issue by Aniket965** [hop-protocol/hop#132]
why is ``` window.fetch``` is used instead of ```node-fetch``` package although it used everywhere else

https://github.com/hop-protocol/hop/blob/724633f6c8128a17f91e428fbe19da2988a92ddb/packages/sdk/src/CoinGecko.ts#L128

**Comment by miguelmota** [comment]
Hi @Aniket965!

Thanks for reporting the issue. It's now using node-fetch as expected.

Closed by https://github.com/hop-protocol/hop/commit/b48556c86115dccb2d3c4d67b30ced33501a5370

**Comment by Aniket965** [comment]
thanks @miguelmota
