### ISSUE TITLE
Wrap component should change the user's network if they are not on the expected network.

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#135]
At this time, the wrap modal tries to send the wrap transaction on the network that the user is currently on. It will not prompt the user to switch their network. This will cause a user to send a transaction on the wrong network.

The wrap/unwrap component should use the MM prompt to let the user switch networks.

**Comment by miguelmota** [comment]
Closed by https://github.com/hop-protocol/hop/commit/21d58ef64c41710dad38d77c09a56b6662d043ab
