### ISSUE TITLE
Bonder: Doesn't bond transactions originating from non-hop smart contracts

### ISSUE THREAD

**Issue by vaibhavchellani** [hop-protocol/hop#137]
Since the bonder node [decodes the transaction input data to determine some things](https://github.com/hop-protocol/hop/blob/ec8175b2e91f1bad0122342d0697f6ed3d29ad0b/packages/hop-node/src/watchers/classes/L2Bridge.ts#L195), if the transaction is made via another smart contract the decoder fails and hence bonding fails.

**Comment by miguelmota** [comment]
@vaibhavchellani Thanks for the bug report! An [update](https://github.com/hop-protocol/hop/commit/f303f1b4d11f032d2feae5d574e1d542a0efeab2) has been applied so it doesn't try to decode the data anymore. 

Our bonders will be able to update with the fix within the next couple of days.
