### ISSUE TITLE
UI: Customize Block Native Modal

### ISSUE THREAD

**Issue by cwhinfrey** [hop-protocol/hop#161]
Use the Hop font and colors to make the BlockNative modal feel more native to the app

Current:
<img width="678" alt="Screen Shot 2021-09-21 at 6 11 41 PM" src="https://user-images.githubusercontent.com/11652019/134267970-ebfc54d4-43c8-4e57-9dca-d080bb904479.png">

Example:
<img width="528" alt="Screenshot 2021-09-21 at 19 23 02" src="https://user-images.githubusercontent.com/11652019/134267995-b94fc524-24d1-4d7b-8a3b-458b760b40bb.png">

**Comment by litodertechie** [comment]
If possible within the constraints of onboard.js we could also blurr the background when the modal opens.

Puts more focus on the modal
<img width="1411" alt="Screenshot 2021-09-22 at 22 30 03" src="https://user-images.githubusercontent.com/30246668/134417989-46c27147-5a8b-4505-b2b2-d49e729933bb.png">
