### ISSUE TITLE
Both App and Landing page: use IPFS and DNSLink

### ISSUE THREAD

**Issue by DaniellMesquita** [hop-protocol/hop#171]

**Comment by miguelmota** [comment]
The app has an IPFS link (may need to be refreshed again)

https://hop-exchange.ipns.dweb.link/

**Comment by miguelmota** [comment]
The IPFS link has been updated and it's set up now to auto-update.

The url ipfs.hop.exchange will redirect to hop-exchange.ipns.dweb.link as well for convenience
