### ISSUE TITLE
When multi-token support?

### ISSUE THREAD

**Issue by DaniellMesquita** [hop-protocol/hop#172]
Currently, it only supports USDC, USDT, MATIC and DAI.

Will it only have whitelisted tokens or also open up for any contract address?

**Comment by BlankerL** [comment]
Seems it will take some time. 

For now, all the tokens should be manually added to the [address file](https://github.com/hop-protocol/hop/blob/develop/packages/core/src/addresses/mainnet.ts). The contract for each token pair should be manually deployed across all the supported networks as well.

**Comment by shanefontaine** [comment]
I am going to close this for now since it doesn't have to do with the codebase :)

Please direct product questions to [Discord](https://discord.gg/PwCF88emV4).
