### ISSUE TITLE
Do not exit bonder if one endpoint is erroring out

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#195]
If the bonder experiences 5 retries for a single call, it exits and restarts (because of Docker). This means that all workers on all chains are restarted.

* The bonder should probably not exit anymore of it is experiencing retries
  * It is important that we don't backoff forever in this case

**Comment by miguelmota** [comment]
Closing as this should already be fixed (https://github.com/hop-protocol/hop/commit/c937f7591a9131d5e3020e6ce85a9fc9da072d71)
