### ISSUE TITLE
UI: Incorrect pool position size

### ISSUE THREAD

**Issue by cwhinfrey** [hop-protocol/hop#205]
On the Pool page in the "Your Position" section, the TOKEN/hTOKEN amount is incorrect. That amount should be the sum of the TOKEN amount and the hTOKEN amount.

![Screen Shot 2021-10-07 at 4 46 33 PM](https://user-images.githubusercontent.com/11652019/136476980-fc93c2e2-0e00-4438-b0b5-3460a081ac8e.png)

In the screenshot, the correct amount would be 2.57 + 3.55 = 6.12

**Comment by miguelmota** [comment]
Closed by https://github.com/hop-protocol/hop/commit/18c5978cf79785c53926d8003451a156a00760a1
