### ISSUE TITLE
UI: Incorrect Pool page position stats

### ISSUE THREAD

**Issue by cwhinfrey** [hop-protocol/hop#207]
Opening a single issue for a couple of issues as they might be related and #205 may be related as well.

1. The "Share of pool" percentage shown when adding to a pool seems to be too high.
2. The TOKEN/hTOKEN, TOKEN, and hTOKEN values all seem to be inaccurate or incorrect.

This may require some research and testing to figure out what's going wrong. Here's what I saw when adding a pool position and then removing it.

The "Share of pool" was quoted at 6.5% for adding 50,000 WMATIC and 50,000 hMATIC

![Screen Shot 2021-10-07 at 5 02 41 PM](https://user-images.githubusercontent.com/11652019/136478842-1e8128a6-b986-4cf4-9820-f79aaf604660.png)

After adding 50,000 WMATIC and 50,000 hMATIC the following position data was shown:
![Screen Shot 2021-10-07 at 5 04 56 PM](https://user-images.githubusercontent.com/11652019/136479298-381427b4-e770-4a10-bde3-07c7da62938c.png)
The WMATIC/hMATIC, WMATIC, hMATIC values are all too small and make it look like funds were lost. The pool share is only 3.36% vs the quoted 6.5% but I believe this is accurate and the quote is wrong.

After removing from the pool, this is what I received. This further supports that the WMATIC/hMATIC, WMATIC, hMATIC values previously shown were wrong because I received more of both.

![Screen Shot 2021-10-07 at 5 10 19 PM](https://user-images.githubusercontent.com/11652019/136479563-300ebffa-b779-479f-ab0c-fbac16876ddf.png)

**Comment by miguelmota** [comment]
Closed by https://github.com/hop-protocol/hop/commit/831ba14ad4fc97a9de3846f84c7a00b40c4d6a28 and https://github.com/hop-protocol/hop/commit/73fdffbce316a66d02405332ebcbc6ac4ffe860f
