### ISSUE TITLE
Guarantee tx is not dropped from mempool by re-broadcasting txs at gasPrice cap

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#212]
We need to handle the case where a transaction sent at the `gasPrice` cap gets dropped from the mempool. We can do this by continuously retrying (at the same cadence as the other boost txs) transaction at the same capped `gasPrice` and either watching it successfully get into the mempool or handling the case where the transaction is "already seen" and ignoring it.

Transactions that are not yet at the cap are fine because they are handled by the native gas boosting—if a transaction was dropped from the mempool, it will simply be replaced by the next boosted tx.

**Comment by miguelmota** [comment]
Closing as this was implemented with https://github.com/hop-protocol/hop/pull/436
