### ISSUE TITLE
Check the available credit for the BondTransferRoot watcher in the DB getter, similar to the BondWithdrawal watcher

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#216]
The BondWithdrawal watcher has an `availableCredit` check that looks at the local state in the DB getter in order to avoid on-chain calls every poll. The BondTransferRoot watcher can use this logic as well in order to avoid the repeated on-chain calls.

**Comment by miguelmota** [comment]
@shanefontaine is this still an issue?

**Comment by shanefontaine** [comment]
@miguelmota Yes it is. The BondTransferRoot watcher should have some logic similar to [this](https://github.com/hop-protocol/hop/blob/d5b56ad8d23f17d8989587bce5d868ea3729495d/packages/hop-node/src/watchers/BondWithdrawalWatcher.ts#L76-L86) in order to optimally send transactions at the appropriate time.

The name/description of this issue was incorrectly worded, so I just updated it.

**Comment by miguelmota** [comment]
Thanks, I'll handle these changes

**Comment by miguelmota** [comment]
Closed by https://github.com/hop-protocol/hop/pull/328
