### ISSUE TITLE
Fix high CPU usage on bonder instances

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#231]
Some bonder instances are using a high % of its available CPU (m3.medium). See logs for more information.

This does not appear to be causing major issues. However, we should optimize CPU read/write so that bonders are not running hot at all times.

**Comment by miguelmota** [comment]
matic bonder (before)

![DeepinScreenshot_select-area_20220325123024](https://user-images.githubusercontent.com/168240/160193224-2d19d4ab-f1f6-4218-bc2e-5d04d8d2915e.png)

matic bonder (after)

![DeepinScreenshot_select-area_20220325130309](https://user-images.githubusercontent.com/168240/160193234-78421957-7909-4023-89af-73bb10db5634.png)

Closed by https://github.com/hop-protocol/hop/commit/87589ecb3f0d18d7f54a433729f04846e0fb6088
