### ISSUE TITLE
Show more detailed warning message when account eth is too low for fee

### ISSUE THREAD

**Issue by miguelmota** [hop-protocol/hop#253]
Expected: Show how much more ETH is required for transaction fee if account already has ETH
Actual: Message states to add ETH to account even though account already has ETH

![DeepinScreenshot_select-area_20211027135335](https://user-images.githubusercontent.com/168240/139145403-8d4d3270-71b2-435d-a996-8b55ff91306b.png)

**Comment by kangarang** [comment]
addressed by: #321
