### ISSUE TITLE
UI: Convert page auto-fills "x.0" which makes it very difficult to type decimal values

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#256]
The convert page auto-fills `x.0` when you type `x` into the input field. Because of this, it is not easy to type in decimals. You cannot delete the `0` after it was auto-filled.

https://user-images.githubusercontent.com/9441295/139483079-b8852abd-9e99-4ac5-962e-289e3f0622b4.mov

**Comment by kangarang** [comment]
fixed: #259
