### ISSUE TITLE
UI: FE should warning based on output instead of price impact warning

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#257]
The frontend currently shows a warning if the price impact of a swap is `>1%`. It might confuse users to see a warning if they are, for example, going to make money on the swap. See image below.

A warning should be shown if the rate is unfavorable and the user will loose money on the swap. I would imagine that a warning would be shown if the user will receive `<99%` of what their input amount is. The warning might say something like: `Warning! Unfavorable rate. Slippage is 1.x%`. 

<img width="711" alt="Screen Shot 2021-10-29 at 8 52 48 AM" src="https://user-images.githubusercontent.com/9441295/139483395-9819bb17-b73b-4f3b-ad16-41f2ee10d412.png">

**Comment by kangarang** [comment]
related: #249
