### ISSUE TITLE
UI: add 20k gaslimit to polygon txs

### ISSUE THREAD

**Issue by kangarang** [hop-protocol/hop#266]
some [transactions](https://polygonscan.com/txs?a=0x76b22b8c1079a44f1211d867d68b1eda76a635a7) are failing for unclear reason. we suspect it is due to polygon's variable gas estimation.

**Comment by shanefontaine** [comment]
@kangarang the Polygon gas estimator does not work in all cases (I suspect it has to do with [the 1/64 rule](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-150.md)). The bonder software [hard-codes excessive gas](https://github.com/hop-protocol/hop/blob/develop/packages/hop-node/src/watchers/classes/L2Bridge.ts#L296-L300) where appropriate. I would imagine the FE needs to as well.

**Comment by kangarang** [comment]
closing for now. can re-open with more details if this happens noticeably again
