### ISSUE TITLE
Convert page "Convert" button should be disabled if L1 Transaction fee is greater than amount being sent

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#272]
The UI currently `enable`s the "Convert" button on the "Convert" page when sending from L2 -> L1 via Hop Bridge even if there is not enough funds being sent to cover the L1 tx fee.

Expected behavior: I would expect the convert button to be disabled and a warning message to be shown if additional funds need to be sent in order to cover the cost of the L1 tx fee.

**Convert page -- bad example**
![Screen Shot 2021-11-04 at 1 57 06 PM](https://user-images.githubusercontent.com/9441295/140419192-0d9b1224-0b37-47b1-a620-53c74f9e276e.png)

**Send page -- good example**
![Screen Shot 2021-11-04 at 1 59 01 PM](https://user-images.githubusercontent.com/9441295/140419168-e9e2cda2-2956-4b42-9752-5382578be8d0.png)

**Comment by miguelmota** [comment]
Fxed on mainnet staging
