### ISSUE TITLE
Send page UI should be fixed in order to avoid buttons moving around & flashing

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#273]
_The video applies to both bugs._

Bug 1:

The buttons on the send page move around based on the current state of the app. For optimal UX, I would expect the buttons to stay in the same spot, even if state is being loaded.

Expected behavior: The "Fees" item should not disappear when loading state. The amount should just be a `-` when loading, similar to the Estimated received.

---

Bug 2:

The send button is quickly `enabled` when it should be `disabled`. 6 seconds into the video, you will see the send button become `enabled` very quickly (~1/2 a second, if that). 

Expected behavior: The send button should always be disabled when loading state.

https://user-images.githubusercontent.com/9441295/140420062-e893e8c5-2d0f-4bca-9078-83c81455147a.mov

**Comment by kangarang** [comment]
addressed: https://github.com/hop-protocol/hop/commit/5560c91438c48eec02b00693d2a269a40a60f141
