### ISSUE TITLE
"Minimum received" units are sometimes incorrect when sending native tokens across chains

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#276]
The "Minimum received" units should reflect what asset is being received on the destination chain. I _think_ it is currently showing the units of the sending chain.

For example, I'd expect the image below to say `0.0030 ETH` instead of `0.0030 WETH` since users will receive ETH on Arbitrum.

<img width="606" alt="Screen Shot 2021-11-10 at 17 35 01" src="https://user-images.githubusercontent.com/9441295/141221377-46390cd9-1cdc-44cd-9fe1-cfd7dc5e4ae5.png">

**Comment by miguelmota** [comment]
it was using source token symbol instead of destination token symbol. Fixed with https://github.com/hop-protocol/hop/commit/3afe0d203a2dc0b99719e21e037cd3dbfad49e0b
