### ISSUE TITLE
UI: submit a report / support button

### ISSUE THREAD

**Issue by kangarang** [hop-protocol/hop#281]
we currently correspond with users via discord for support issues. this takes time and mental overhead. we should add a button that sends us the context we need to support our users better.

contextual data: error message, screenshot, tx hash, url params, version numbers (GUI, browser, metamask)

**Comment by shanefontaine** [comment]
One consideration: many users will say something on discord and then say nevermind a few minutes later when the transaction comes through. If we had this button, I believe we may get a handful of false positives.

**Comment by miguelmota** [comment]
Closing issue since the number of ui support issues has been minimal as the ui has become more stable over time
