### ISSUE TITLE
How to use another contract to call the hop contract

### ISSUE THREAD

**Issue by jinyang1994** [hop-protocol/hop#312]
I want to do some operations(eg: swap X token for USDC) through my contract, and then cross-chain, how should I do it?

**Comment by shanefontaine** [comment]
Hey @jinyang1994 ! There are a few different variables when interacting directly with the contracts. It would be best to take a look at [our "Direct Contract Integration" guide](https://authereum.notion.site/Hop-Direct-Contract-Integration-b3a7030ba9264ae79d96087dec448d10) for integrators. Alternatively, you can take a look at how the [SDK interacts with the contracts](https://docs.hop.exchange/js-sdk) and copy that interaction.

I'm going to close this issue now, but feel free to start a conversation over in our [Discord](https://t.co/p72EXP2HB2) after you've got a chance to take a look at the links above!

**Comment by jinyang1994** [comment]
Thank you for your reply, have you considered using `populateTransaction` to generate `tx data` so that users can decide when to send transactions?
