### ISSUE TITLE
Max button rewording

### ISSUE THREAD

**Issue by lukerhoads** [hop-protocol/hop#322]
Hello,

Do you guys think that the "MAX" button on the send input is not worded correctly? When clicked, it gives the minimum required amount needed to add to the balance to cover estimated fees. I am not sure if this is the desired functionality. 

Example
![hop](https://user-images.githubusercontent.com/51463884/146067911-8380bdf1-714b-498a-97c2-69211a714401.png)

In this image, when you click the max button it gives you the balance you are short. The estimated fees were 0.0076631 eth, and the balance is 0.0026142 eth. The max shows the difference, but the warning below should show the amount that needs to be added. The input should show the balance of the account, right?

Let me know if I am missing something.

Thanks

**Comment by miguelmota** [comment]
Hi @lukerhoads, thanks for pointing this out. It's definitely a bug where the calculated amount is negative (balance - estimatedGasCost). We'll get this fixed as soon as possible. Thanks!

**Comment by miguelmota** [comment]
Closed by https://github.com/hop-protocol/hop/commit/77565b0391ff85931978c9fdd2f51401da971689
