### ISSUE TITLE
The hop-node package should not read the `bonder` addresses from the `core` package

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#329]
The `hop-node` package currently reads the `bonder` addresses from the `core` package. However, the bonder should only be concerned about themself and being aware of other bonders is unnecessary except for the available credit watcher. Maybe the available credit watcher can read bonder addresses from the local config.

This fix should achieve two things:
* Bonder software should not rely on bonder addresses from `core` package
* Available credit watcher should still work as expected

**Comment by miguelmota** [comment]
Closed by https://github.com/hop-protocol/hop/pull/365
