### ISSUE TITLE
Pre-optimism regenesis transfers and transferRoots loop through `populate...()` functions repeatedly on a new sync

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#331]
With a new sync, pre-optimism regenesis transfers and transferRoots loop through `populate...()` functions repeatedly. You can see this on the `2f51ac4bd89013b2a23ebc4e9ec20a21b6b461f8ede2b8ae54cddeacf5cbfa2a` log stream of the ETH bonder by searching for "populating" and observing the same ID or root being populated repeatedly. **This is non-blocking and everything continues to work, however, I believe many, many RPC calls are used in this case.**

I believe the intended behavior is to ignore the IDs and roots if the `populate...method()` after attempting a populate one time.

To reproduce, perform a fresh sync (of ETH) and then watch the logs attempt to populate the DB items repeatedly.

**Comment by miguelmota** [comment]
In the case of pre-regenesis transfers and roots, I think it'd be best to store the list of transfer ids and transfer root ids in a file and have the db getters ignore them so it doesn't attempt to process them at all to save resources since we know that they won't exist and can't be processed at all.

For any other transfer ids or transfer root ids, they can be marked as notFound after initial attempt failure (not due to rate limit error)

**Comment by shanefontaine** [comment]
> For any other transfer ids or transfer root ids, they can be marked as notFound after initial attempt failure

I believe this is the intended behavior, but, I believe the logs at this time show that this is not happening as expected. I believe this is the piece that needs to be understood and resolved, as this is what I believe the intention is even before this issue was opened.

> In the case of pre-regenesis transfers and roots

I believe we need to design it in such a way that we should be able to function fine even with a regenesis. I know Optimism is planning at least one more and xDai/Gnosis have multiple regenesis on their roadmap. I'd imagine all other chains will do something similar too.

I think just marking as `notFound` is totally fine here and we can ignore the manual list. This may just be premature-optimization-thinking though. Curious about your thoughts here.

**Comment by shanefontaine** [comment]
For example, searching for "expected timestamped key. incomplete transfer" in the current ETH running log stream `b274c3658a3ff4613eda2caa2b51939f73941d264e07089bdeb79cbe821889c0` will produce many items that I would not expect to be there.

**Comment by miguelmota** [comment]
Closed by https://github.com/hop-protocol/hop/pull/376
