### ISSUE TITLE
Multiple settlements are not correctly accounted for

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#333]
The code currently assumes a single `SettleMultipleWithdrawals` per transfer. The reality is that this event can be emitted multiple times for a single root. This assumption is seen in the fact that `db.transferRoots.multipleWithdrawalsSettledTxHash` can  be ovwerritten [here](https://github.com/hop-protocol/hop/blob/f10a3234399581b021239e4fbfb39c135f8bc50e/packages/hop-node/src/watchers/SyncWatcher.ts#L1090) when a new event is seen. Additionally, `db.transferRoots.multipleWithdrawalsSettledTotalAmount` overwrites the value [here](https://github.com/hop-protocol/hop/blob/f10a3234399581b021239e4fbfb39c135f8bc50e/packages/hop-node/src/watchers/SyncWatcher.ts#L1091) when it really should add to the existing value.

I'm not aware of all the implications of this change, so they will have to be thought through carefully.

**Comment by miguelmota** [comment]
Closed by https://github.com/hop-protocol/hop/pull/380
