### ISSUE TITLE
The bonder does not account for the `WithdrawalBondSettled` event

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#334]
The bonder software does not account for a `WithdrawalBondSettled` event. The event handler should be added and the appropriate changes should be made in the code to reflect this. I believe there may be quite a few changes that must be made. This event can be emitted multiple times per root hash, but only once per transferId, so take into account similar behavior as mentioned in #333 .

This will be more intricate than reading the event params and writing to the DB. Some, noninclusive reasons:
* `amount` needs to be retrieved from another on-chain call since it is not returned from the event so that it can be added to `multipleWithdrawalsSettledTotalAmount` in the DB.
  * The `amount` is cleared from the [`_bondedWithdrawalAmounts`](https://github.com/hop-protocol/contracts/blob/master/contracts/bridges/Bridge.sol#L274) when this function is called, so we cannot get it from there.
* There may need to be additional DB keys added that reflect what happens when this event gets emitted.

**Comment by miguelmota** [comment]
PR https://github.com/hop-protocol/hop/pull/380

**Comment by miguelmota** [comment]
Closed by https://github.com/hop-protocol/hop/pull/380
