### ISSUE TITLE
The bonder should not start if the config file is not correctly populated

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#337]
_Up for discussion._

There have been issues where config files are not correctly populated and the bonder software defaults to a non-ideal value. The most extreme case of this is the `waitConfirmations` defaulting to `0` and putting a bonder at risk of a reorg.

I believe the bonder software should be very explicit about these values and whoever is running the bonder should input these value intentionally. I believe the bonder software should not start unless these values are explicitly defined in the config. Very rarely will any default values apply to all cases, as bonder liquidity, risk tolerance, fees, etc. are all on a per-bonder bases.

Some config options that this applies to:
_**This is not an inclusive list. Please independently review any other potential config options that might apply.**_
* `minThresholdAmount`
* `fees`
* `routes`
* `roles`
* `watchers`
* `chains`
* `waitConfirmations`

**Comment by miguelmota** [comment]
Since `minThresholdAmount` is only required for the `CommitTransfersWatcher` and `fees` is `BondWithdrawalWatcher`, then does it make sense to only require those if those watchers are enabled?

**Comment by shanefontaine** [comment]
Yes, good call. I think that would be ideal.

**Comment by miguelmota** [comment]
Closed by https://github.com/hop-protocol/hop/pull/346
