### ISSUE TITLE
`transferSentIndex` should be used correctly in the `handleTransferSentEvent()` function

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#342]
We currently [store a `transferSentIndex`](https://github.com/hop-protocol/hop/blob/f10a3234399581b021239e4fbfb39c135f8bc50e/packages/hop-node/src/watchers/SyncWatcher.ts#L421) in the transfersDb. However, the value we are using is actually the `transactionIndex` (index of the transaction in the block) instead of the `index` (index of the transfer in the root). We should be storing the `index` (probably with a more descriptive title in the DB, such as `transferIndex`) in the DB. It is unclear if we still need the `transactionIndex`.

This is sensitive, as I believe we use this value to order transfers for a root, among other things.

**Comment by miguelmota** [comment]
Updated to use `index` for event arg instead of transaction index in commit https://github.com/hop-protocol/hop/commit/314434d60e8ddd7f407c25019dd6283f757aab1b

**Comment by shanefontaine** [comment]
Are any changes required [here](https://github.com/hop-protocol/hop/blob/314434d60e8ddd7f407c25019dd6283f757aab1b/packages/hop-node/src/db/TransfersDb.ts#L275-L276) based on this update?

**Comment by miguelmota** [comment]
I don't think there would be any implications with that one because the db getter sorts them by block number first, and if and only if the block number is the same then it sorts by index, so the update should be good since that's the only place `transferSentIndex` is used

**Comment by shanefontaine** [comment]
SGTM 👍   Going to close now.
