### ISSUE TITLE
The return type of `txOverrides` should be consistent

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#343]
Update [`txOverrides()`](https://github.com/hop-protocol/hop/blob/f10a3234399581b021239e4fbfb39c135f8bc50e/packages/hop-node/src/watchers/classes/ContractBase.ts#L139) to return `Promise<Record<string, BigNumber>>`. It currently returns `Promise<any>` and we return different types depending on the case.

For example, when it is `mainnet`, we return `string`s, but for all else we return `number`s.

**Comment by miguelmota** [comment]
Types clean up commit https://github.com/hop-protocol/hop/commit/97c2412d896aa5d3407b67ce01036e8c04a941e8

**Comment by shanefontaine** [comment]
LGTM 👍  Going to close.
