### ISSUE TITLE
The `Transfer` and `TransferRoot` types should have at least one key that is not optional

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#344]
Currently, all keys of type `Transfer` and `TransferRoot` are optional. At a very minimum, I believe `transferId` (in `Transfer` type) and `transferRootId` (in `TrasferRoot` type) should not be optional. If ever there was a time where these were undefined, our bonder would not work. Defining these also gives the added benefits of simplicity because we can:
* Remove all `non-null assertion` and linting ignore statements related to these items
* Remove all `if (!transferId)` and `if (!transferRootId)` checks

Note, there are other keys that probably should be required as well, but it might be too annoying to do this in practice. It is worth evaluating this prior to implementation.

**Comment by miguelmota** [comment]
The identifying keys (`transferId` or `transferRootId`) are assigned in the `update` function (see [here](https://github.com/hop-protocol/hop/blob/5c54a41d8f98b16ea1c86bc79bda753dfe62a2c5/packages/hop-node/src/db/TransfersDb.ts#L200) and [here](https://github.com/hop-protocol/hop/blob/5c54a41d8f98b16ea1c86bc79bda753dfe62a2c5/packages/hop-node/src/db/TransferRootsDb.ts#L314) respectively). They should never be `undefined` in this case. Agree that the null checks should be removed

**Comment by miguelmota** [comment]
Commit to clean up the assertion eslint comments and removes unnecessary conditional checks

https://github.com/hop-protocol/hop/commit/0b9d5f466eef5373f4186568ac159f81d090ed30

**Comment by shanefontaine** [comment]
Sorry for the confusion. I meant that I believe the `non-null assertion` checks should still exist. I think that is good practice and that Typescript should enforce this so that we handle things correctly at compile time.

My suggestion here was to:
* remove the optional indicator [here](https://github.com/hop-protocol/hop/blob/0b9d5f466eef5373f4186568ac159f81d090ed30/packages/hop-node/src/db/TransfersDb.ts#L8) and [here](https://github.com/hop-protocol/hop/blob/0b9d5f466eef5373f4186568ac159f81d090ed30/packages/hop-node/src/db/TransfersDb.ts#L8) so that we are forced to use it correctly throughout
* remove the actual `!` from the code where appropriate, not just the `// eslint-disable-line @typescript-eslint/no-non-null-assertion` comment.

I think it makes sense to keep Typescript checks pretty tight so that we are forced standardize our code and make it easier to iterate on.

@miguelmota

**Comment by miguelmota** [comment]
> remove the optional indicator here and here so that we are forced to use those keys correctly throughout

That would mean passing `transferId` or `transferRootId` on every `update` which seems redundant considering those are the primary keys which get set automatically. Maybe for the update only then those are optional since the update can't occur anyway without the primary key.

**Comment by shanefontaine** [comment]
> Maybe for the update only then those are optional

I think that might be super reasonable, if the implementation is reasonable! I like that a lot.

IMO doing this would help new contributors reason about the intentions of the DB a little easier by handling various issues at compile time. 

I'm totally fine too if you think this is bikeshedding and should be pushed off to a later time! My current thinking is that we are at a good point to start tightening down pieces of our code so that we start using TypeScript more ideally so that we catch more at compile-time, but if you think it is premature, I'm happy to take your side on this one.

**Comment by miguelmota** [comment]
Closed by https://github.com/hop-protocol/hop/pull/351
