### ISSUE TITLE
Additional CLI functionality

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#348]
The CLI could use the following functionality:

- [ ] (`swap`) Implement nativeToken -> wToken (`deposit`) on all chains
- [ ] (`swap`) Implement nativeToken -> hToken on all chains
- [ ] (`swap`) Implement hToken -> nativeToken on all chains
  * I believe this would be two steps: hToken -> canonicalToken then canonicalToken -> nativeToken 
- [x] (`send` and `swap`) implement `--max` when sending or swapping from a native token
  * I believe this means that we would simply take (`balance - (gasLimit * gasPrice)`)
- [ ] (`swap`) Add ability to swap on [Uniswap on Polygon](https://twitter.com/Uniswap/status/1472200289919053826)
- [ ] (`swap`) Update [Uniswap addresses](https://github.com/hop-protocol/hop/blob/314434d60e8ddd7f407c25019dd6283f757aab1b/packages/hop-node/src/uniswap/swap.ts#L134-L159) to make available all of Hop's supported assets on more chains, if liquid
- [ ] If reasonable, allow for two-way Uniswap swaps (i.e. ETH -> USDC or USDC -> ETH). I believe we only support token -> native right now.
- [ ] (`send`) Sending the native asset with [`sendTokens`](https://github.com/hop-protocol/hop/blob/314434d60e8ddd7f407c25019dd6283f757aab1b/packages/hop-node/src/cli/send.ts#L161) does not work as intended. It errors out on the [balance check](https://github.com/hop-protocol/hop/blob/314434d60e8ddd7f407c25019dd6283f757aab1b/packages/hop-node/src/cli/send.ts#L212) because the balance check takes into account the wrapped token and not the native asset. The `tokenClass` should be updated to use the native token, not the wrapped token.
  * Please verify that this is still an issue prior to implementing a fix

**Comment by miguelmota** [comment]
all the bullets should be handled by this [pr](https://github.com/hop-protocol/hop/pull/398)
