### ISSUE TITLE
I think hop can win this gitcoin bounty

### ISSUE THREAD

**Issue by eltNEG** [hop-protocol/hop#358]
Hello guys. I discovered this amazing project when I was searching for existing solutions before I start working on this gitcoin bounty (https://gitcoin.co/issue/gitcoinco/skunkworks/253/100027342). 

I think that it is better to contibute to hop and make it better instead of reinventing the wheel. Also, by participating in the bounty, I believe hop will get a better visibility, that it deserves, in the ethereum community.

**Comment by miguelmota** [comment]
Closing as stale issue
