### ISSUE TITLE
UI: handle cases where the ENS avatar image link is broken

### ISSUE THREAD

**Issue by litodertechie** [hop-protocol/hop#381]
<img width="124" alt="Screenshot 2022-01-20 at 17 16 17" src="https://user-images.githubusercontent.com/30246668/150368284-f4df4828-a057-4301-ad4e-f7f1469b674e.png">
How uniswap handles a broken link

<img width="388" alt="Screenshot 2022-01-20 at 13 47 28" src="https://user-images.githubusercontent.com/30246668/150368416-f107283f-a281-4543-bb1d-2d590e349cfd.png">
How hop handles a broken link

**Comment by peter44-a** [comment]
> <img width="124" alt="Screenshot 2022-01-20 at 17 16 17" src="https://user-images.githubusercontent.com/30246668/150368284-f4df4828-a057-4301-ad4e-f7f1469b674e.png">
> How uniswap handles a broken link
> 
> <img width="388" alt="Screenshot 2022-01-20 at 13 47 28" src="https://user-images.githubusercontent.com/30246668/150368416-f107283f-a281-4543-bb1d-2d590e349cfd.png">
> How hop handles a broken link

Hello has your issue been resolved?
