### ISSUE TITLE
Handle chain-specific exit errors

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#383]
[This `try...catch`](https://github.com/hop-protocol/hop/commit/e06a4942c705eb65f0e7e58ad4f69ecf78fc0491) was introduced to account for [this](https://github.com/maticnetwork/matic.js/discussions/312#discussioncomment-2018951) Polygon error. Without the `try...catch`, failing in `relayXDomainMessage()` killed the bonder.

The `try...catch` was added as a temp fix, but, more broadly, all exit watchers should be standardized and handle these types of errors. At an absolute minimum, they should not kill the bonder if they error out.

**Comment by shanefontaine** [comment]
The (old) Polygon SDK does not allow for `try...catch`, as described above. I believe it is because of [this](https://stackoverflow.com/a/47163758/10378715). The current implementation is just a [block list](https://github.com/hop-protocol/hop/commit/a58995ad96eaef511fddf9fa52be247405702c80) that should be removed when this issue is resolved.

**Comment by miguelmota** [comment]
Updating the old polygon sdk patch version seems to have fixed the issue where it kills the bonder because of an uncaught error
