### ISSUE TITLE
UI: Wait confirmations is not respected in the UI

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#402]
When waiting for a certain number of confirmations after a tx, the UI sometimes shows that all confirmations are met even when it is not the case.

https://user-images.githubusercontent.com/9441295/156392444-75ab0d7c-7dcd-4919-a11d-cfb8eb071f67.mov

**Comment by miguelmota** [comment]
Closing since confirmations are no longer shown there and that component be replaced by account history
