### ISSUE TITLE
Bonder appears to sync from block 1 on every sync iteration on Optimism

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#418]
The bonder software appears to sync from block 1 on Optimism for every sync iteration. The expected result is to sync from the last-synced spot.

![Screen Shot 2022-03-25 at 13 06 23](https://user-images.githubusercontent.com/9441295/160194755-dcee504b-19c6-44ca-b5fa-f7d435e1bf43.png)

This was observed on the mainnet bonder and on the ETH bonder. It may be on every bonder, however, it has not been confirmed. Based on some investigation, this _may_ just be a display issue and the actual syncing from the last-synced spot is working as expected. Some data to back this up:

* The Alchemy dashboard shows that we do `getLogs` with small block ranges, as expected. See image below.
* The Alchemy usage page shows the Optimism uses less compute units than most other chains, which I would not expect if we were resyncing from `1` every minute.
* Every other chain appears to work, and the code is simple enough that I would expect this to either work or not work for _all_ chains.

![Screen Shot 2022-03-25 at 13 17 15](https://user-images.githubusercontent.com/9441295/160195015-7d047944-347e-4fd9-a9cb-b326f8636e4f.png)

**Comment by miguelmota** [comment]
The [log](https://github.com/hop-protocol/hop/blob/87589ecb3f0d18d7f54a433729f04846e0fb6088/packages/hop-node/src/watchers/SyncWatcher.ts#L218) is simply logging the [`bridgeDeployedBlockNumber`](https://github.com/hop-protocol/hop/blob/87589ecb3f0d18d7f54a433729f04846e0fb6088/packages/core/src/addresses/mainnet.ts#L286) as `startBlockNumber`. The [`getBlockValues`](https://github.com/hop-protocol/hop/blob/87589ecb3f0d18d7f54a433729f04846e0fb6088/packages/hop-node/src/watchers/classes/Bridge.ts#L545) method shows it's uses `latestBlockSynced` if it exists so I don't think it's reading from block 1 on every sync

The log message has been updated 

https://github.com/hop-protocol/hop/commit/0baa1677aa3d477ebdd1c3cf642993556301a481

**Comment by shanefontaine** [comment]
You are correct and I was misinterpreting that log. Thank you for the clarification and the updated message. Closing now.
