### ISSUE TITLE
`Withdraw` page throws an error when trying to withdraw a transfer

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#421]
I tested this with both a transfer that had been `set` on the destination chain as well as one that had not yet been committed on the source chain. The error is `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sourceChain')`.

https://user-images.githubusercontent.com/9441295/161133937-7dac3a2c-fe1d-4902-9824-195d31d4df6c.mov

**Comment by miguelmota** [comment]
Closed by https://github.com/hop-protocol/hop/commit/8502531144feaaf00df209f2dd8426dad982dcad
