### ISSUE TITLE
sdk: add buffer gas to polygon txs in txOverrides

### ISSUE THREAD

**Issue by kangarang** [hop-protocol/hop#423]
currently, the sdk adds [buffer gas](https://github.com/hop-protocol/hop/blob/develop/packages/sdk/src/AMM.ts#L135) to polygon txs in AMM.ts, but not in HopBridge.ts. setting this value within `txOverrides` should in theory be the cleanest approach to resolving [recent issues](https://polygonscan.com/address/0xc315239cfb05f1e130e7e28e603cea4c014c57f0) involving failed txs on polygon.

additionally, [`StakeWidget`](https://github.com/hop-protocol/hop/blob/develop/packages/frontend/src/pages/Stake/StakeWidget.tsx) should be upgraded as well, as the methods are called directly

**Comment by miguelmota** [comment]
Closing as this is no longer as issue
