### ISSUE TITLE
Type issues in version 0.0.1-beta.314

### ISSUE THREAD

**Issue by mathiasmoeller** [hop-protocol/hop#429]
I just upgrade from `0.0.1-beta.310` to `0.0.1-beta.314`.
When compiling my project I get the following errors:
<img width="1352" alt="Screen Shot 2022-05-02 at 14 34 21" src="https://user-images.githubusercontent.com/8833906/166234381-2c188208-5cad-4db0-b773-92bde3ef47fc.png">

It looks like the relative file paths to the types files are incorrect.
Please let me know if you need more information but it seems pretty straight forward :)

**Comment by miguelmota** [comment]
@mathiasmoeller thanks for the bug report. I tried that following and it seems to work with `esModuleInterop` enabled. (there's an import [issue](https://github.com/primus/eventemitter3/pull/244#issuecomment-1022330019) related to eventemitter3 which requires the interop flag)

install latest version

```sh
npm i @hop-protocol/sdk@latest --save
```

`index.ts`

```ts
import { Hop } from '@hop-protocol/sdk'

console.log(Hop)
```

compile (should show no errors)

```sh
npx tsc --esModuleInterop index.ts
```

**Comment by mathiasmoeller** [comment]
Hey @miguelmota 
Sorry for not replying for so long! I was on vacation and afterwards I forgot about it.
I tried newer versions now since `0.0.1-beta.314` is already outdated.
The `--esModuleInterop` flag helps for `0.0.1-beta.316`, but on `0.0.1-beta.317` it still fails:
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/8833906/171163038-4297566b-a723-4135-945c-c3da09b6ee7f.png">
I could reproduce the same behaviour on our CI.
Could you check if you can reproduce it on your end?

Thanks a lot!
