### ISSUE TITLE
Error: rpcUrl could not be found for network: arbitrum

### ISSUE THREAD

**Issue by zzq0826** [hop-protocol/hop#440]
hello.  I want to test on kovan testnet. but it throw the error. `Error: rpcUrl could not be found for network: arbitrum`. 
i just run `REACT_APP_NETWORK=kovab yarn run dev`
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/12936800/175804496-f5100fcc-6fff-4886-ba54-d1593857b012.png">
and when i tested online `https://kovan.hop.exchange/send?token=USDC&sourceNetwork=ethereum&destNetwork=xdai`, i had some usdc. but it did not show.

thx for your help.

**Comment by miguelmota** [comment]
The only supported network on kovan is gnosis chain (xDai) so you need to update the env var `REACT_APP_ENABLED_CHAINS=ethereum,gnosis`
