### ISSUE TITLE
replace lerna and netlify with pnpm and vercel.

### ISSUE THREAD

**Issue by zhyd1997** [hop-protocol/hop#441]
- why replace `lerna` with `pnpm`:
  - more faster
- why replace `netlify` with `vercel`:
  - `netlify` has some problems with `pnpm` and
  - `vercel` supports `pnpm` by default.

**Comment by miguelmota** [comment]
1. nice I'll check out pnpm
2. The live frontend is actually built using github actions and is served by IPFS (so no need for netlify/vercel)
