### ISSUE TITLE
Type issue in all versions since `0.0.1-beta.316`

### ISSUE THREAD

**Issue by mathiasmoeller** [hop-protocol/hop#445]
As already reported [here](https://github.com/hop-protocol/hop/issues/429) I am still getting TS erros for all versions since 316. Currently I'm testing `0.0.1-beta.330`.

When I run `tsc --esModuleInterop` I get the following errors:
![Screen Shot 2022-07-11 at 14 24 12](https://user-images.githubusercontent.com/8833906/178263587-e9e1d5d3-d16e-46e5-84e5-5d3349bc9110.png)
It looks like the relative path that is used in the files (In the case of the first error in `AMM.d.ts` it's `'@src/../../core/contracts/Swap`) is broken.
For me, the `@src` reference in the path leads to `node_modules/@types`.
The referencing file is in `node_modules/@hop-protocol/sdk/dist/src/AMM.d.ts` and the referenced `Swap` types are in `node_modules/@hop-protocol/core/contracts/Swap.d.ts.map`

I don't have any custom linking or anything set up locally. 

Could this be a path issue that only works on your specific setup?

**Comment by mathiasmoeller** [comment]
Still happening for version `0.0.1-beta.331`. Any one here who could look into this?

**Comment by miguelmota** [comment]
@mathiasmoeller thanks for the follow up; can you create an example repo that replicates the issue?

**Comment by miguelmota** [comment]
@mathiasmoeller can you try `@hop-protocol/sdk@0.0.1-beta.332`?

**Comment by mathiasmoeller** [comment]
Hey @miguelmota , version 332 works like a charm! Thanks a lot 💪

**Comment by miguelmota** [comment]
thanks for confirming @mathiasmoeller!
