### ISSUE TITLE
Send Token UI : the form should support deeplinking all URL params for a better UX

### ISSUE THREAD

**Issue by dewanshparashar** [hop-protocol/hop#459]
### Objective
For a seamless user experience, coming to https://app.hop.exchange/#/send from other apps, most of the form data should be prefilled from the URL itself. `https://app.hop.exchange/#/send?sourceNetwork=${from}&destNetwork=${to}&token=${symbol}&amount=${amount}`

### Reproduce
URL: https://app.hop.exchange/#/send?sourceNetwork=ethereum&destNetwork=arbitrum&token=eth&amount=100
Most of the values in the URL still render an empty form - making the user fill in all the info again.

<img height="200px" src="https://user-images.githubusercontent.com/7558499/191067791-0f3014da-98da-442e-93f1-9fb0b1865ee4.png" />

### Code
In the code: `https://github.com/hop-protocol/hop/blob/develop/packages/frontend/src/pages/Send/Send.tsx`, we are extracting `sourceNetwork ` and `destNetwork` from the URL using `useQueryParams`. Similarly, we should have a provision to extract out and set in form, `tokenSymbol` and `tokenAmount`from URL

**Comment by miguelmota** [comment]
@dewanshparashar the `sourceNetwork`, `destNetwork`, `token`, and `amount` query params should all be working as expected on the send page now but let me know if you see any issues
