### ISSUE TITLE
Wrong token symbol

### ISSUE THREAD

**Issue by mdfalcon104** [hop-protocol/hop#474]
Arbitrum one: 
0x82aF49447D8a07e3bd95BD0d56f35241523fBab1 - should be WETH not ETH

xDai
0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1  - should be WETH not ETH

Please check other bridges as well.

**Comment by miguelmota** [comment]
Hi @dlpigpen, can you elaborate on where the issue occurs?

**Comment by mdfalcon104** [comment]
> 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1

Hey as the link to https://arbiscan.io/address/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1. This is the WETH symbol, not ETH.
I tried to use your sdk and traced the token symbol with ETH but it returns the wrapped native ETH contract address. It should be zero address or 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.

**Comment by Johnyratobravo** [comment]
> Arbitrum um: 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1 - deve ser WETH, não ETH
> 
> xDai 0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1 - deve ser WETH, não ETH
> 
> Por favor, verifique outras pontes também.

**Comment by shanefontaine** [comment]
Closing since this is stale. Please create a new issue with additional details if there is still an issue.
