### ISSUE TITLE
getSendData triggers same rpc call twice

### ISSUE THREAD

**Issue by maxklenk** [hop-protocol/hop#476]
In the implemenation of [HopBridge.ts](https://github.com/hop-protocol/hop/blob/develop/packages/sdk/src/HopBridge.ts#L710-L750) - `getSendData` the `amountOut` is requests twice using the same function with the same parameters. Both functions will trigger an rpc request to load data from chain. Please only call it once and use the result for both variables.

```ts
const amountOutWithoutFeePromise = this.calcFromHTokenAmount(
      hTokenAmount,
      destinationChain
    )

const calcFromHTokenPromise = this.calcFromHTokenAmount(
      hTokenAmount,
      destinationChain
    )
```

**Comment by miguelmota** [comment]
nice catch! the duplicated call has been fixed

**Comment by alieltareb1** [comment]
Hello
