### ISSUE TITLE
Process Undefined in hop-protocol/sdk

### ISSUE THREAD

**Issue by mohibrehman31** [hop-protocol/hop#506]
I am using @hop-protocol/sdk@0.0.1-beta.524 . Facing issues in my vite project of process undefined.
Reproduction:
Uncaught ReferenceError: process is not defined
at node_modules/@hop-protocol/sdk/dist/src/config/config.js
========================
exports.etherscanApiKeys = {
    ethereum: (_a = process.env.ETHERSCAN_ETHEREUM_API_KEY) !== null && _a !== void 0 ? _a : '',
    polygon: (_b = process.env.ETHERSCAN_POLYGON_API_KEY) !== null && _b !== void 0 ? _b : '',
    optimism: (_c = process.env.ETHERSCAN_OPTIMISM_API_KEY) !== null && _c !== void 0 ? _c : '',
    arbitrum: (_d = process.env.ETHERSCAN_ARBITRUM_API_KEY) !== null && _d !== void 0 ? _d : '',
    gnosis: (_e = process.env.ETHERSCAN_GNOSIS_API_KEY) !== null && _e !== void 0 ? _e : '',
    nova: (_f = process.env.ETHERSCAN_NOVA_API_KEY) !== null && _f !== void 0 ? _f : '',
    base: (_g = process.env.ETHERSCAN_BASE_API_KEY) !== null && _g !== void 0 ? _g : ''
};

**Comment by Shaharyar417** [comment]
I am facing the same issue.

**Comment by web3dopamine** [comment]
facing same issue

**Comment by shanefontaine** [comment]
@mohibrehman31 @Shaharyar417 can you please provide more information? Can you please provide steps to reproduce the issue?
