### ISSUE TITLE
Hard Coded 500000 gas Limit Causing Issues When Bridging to Optimism

### ISSUE THREAD

**Issue by zdenham** [hop-protocol/hop#510]
Hop SDK hard codes a 500000 gas limit when bridging ether to optimism. This appears to be an unnecessarily high gas limit, and  causes issues with my use case (trying to send the maximum balance via the hop sdk). The overestimate leads to unwanted "leftover funds" when the gas is refunded on the mainnet EOA. 

In practice, these transactions are taking 120000 gas, is there some variable here I'm missing?

**Comment by zdenham** [comment]
Gas estimation continues to be an issue on optimism for us. We will likely need to move away from Hop as a result unfortunately

**Comment by miguelmota** [comment]
The reason for the hardcoded limit is because the transaction fails due to ethers estimating too low (example txs [1](https://etherscan.io/tx/0xd47cab86f881cb1961fbfc086c5d65b826d1bb20a4a6e543efcc81756027020e), [2](https://etherscan.io/tx/0xfb0958b170aebb5dae1fa3d359e40d2cb5eecb455ee03674df97a0486d8652a5)). 

You can however specify your own gas limit or let ethers estimate it for you. Example:

```js
const { Hop } = require('@hop-protocol/sdk')
const ethers = require('ethers')
require('dotenv').config()

async function main() {
  const hop = new Hop('mainnet')
  const privateKey = process.env.PRIVATE_KEY
  const provider = new ethers.providers.getDefaultProvider('mainnet')
  const signer = new ethers.Wallet(privateKey, provider)
  const bridge = hop.connect(signer).bridge('ETH')

  const txData = await bridge.populateSendTx(ethers.utils.parseUnits('0.01', 18), 'ethereum', 'optimism')

  // txData.gasLimit = 150_000 // your own custom gas limit
  delete txData.gasLimit // let ethers estimate gas limit
  console.log(txData)

  const tx = await signer.sendTransaction(txData)
  console.log(tx)
}

main().catch(console.error)
```

We're planning on removing the hardcoded value once the rpc providers return a more reliable gas limit for Optimism and Base, since currently it fails with estimated gas limit and users aren't able to perform transfers.

**Comment by zdenham** [comment]
I see, thank you for the response--will give this a whirl. Previously we had modified the code to use the gas estimation from `populateSendTx` but were running into the underestimate of gas limit like you mentioned, interesting that the underlying issue is ethers.

500000 though was too high for us because we were trying to do a full sweep of `max` native ether, anecdotally 170000 seems to be a more reasonable hardcoded limit at least for OP

**Comment by zdenham** [comment]
Even when using the above approach, sending the transaction always fails with:

```Error: insufficient funds for intrinsic transaction cost [ See: https://links.ethers.org/v5-errors-INSUFFICIENT_FUNDS ] (error={"rawMessage":"Error forwarded from node: insufficient funds for gas * price + value: balance 3390584819344368, tx cost 8351900601944368, overshot 4961315782600000","code":-32603,"message":"Magic RPC Error: [-32603] Error forwarded from node: insufficient funds for gas * price + value: balance 3390584819344368, tx cost 8351900601944368, overshot 4961315782600000"}, method="sendTransaction", transaction=undefined, code=INSUFFICIENT_FUNDS, version=providers/5.7.0)```

When trying to do a full sweep... it seems something about the bridge transaction causes ethers to overestimate the txn cost and return early (before even submitting to the network where it would presumably fail)

**Comment by zdenham** [comment]
I have confirmed with successful transactions the cost is no where near `8351900601944368` wei

**Comment by zdenham** [comment]
Actually, once we also specified other gas parameters such as `maxFeePerGas` and `maxPriorityFeePerGas` which aligned with our gas estimation it started working. 

The issue seemed to be with gas spiking as the txn was submitted.

**Comment by zdenham** [comment]
Thanks for the support!
