### ISSUE TITLE
Update FE and SDK to support Sepolia

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#521]
Support for various testnets on the FE has worked in the past but has not been used in over a year. Now that Sepolia is becoming a main testnet, we should be able to support it with relative ease.

Multiple testnets should be able to live in parallel. For example, there will likely be a time when we support both Goerli and Sepolia, so being able to run them both in parallel would be important. Given difficulties with incentives on testnet, it may be the case that a new testnet will be just around the corner as well.

As a data point, there is a world in the future where ephemeral testnets are spun up and torn down. I do not think there will ever be a time when the Hop UI will support these chains, but I think is worth being aware of during this design.

### Goals

* Update FE to support new testnets with just an env var and updated config file (if possible)
* Update SDK to support new testnets with an updated config file (if possible)

### Considerations

* There are a number of places where the `chainId` of `5` is hardcoded that will not be applicable with multiple testnet support.
* There are a number of places where the string `goerli` is hardcoded.
* It may be the case that some of the code was written with a two-network system in mind (one mainnet, one testnet). It is unclear if there is any actual code that reflects this, but any situation where this binary thinking might have made it into the codebase would need to be udpated (sorry this is so abstract 🙃 )

**Comment by miguelmota** [comment]
Resolved with https://github.com/hop-protocol/hop/commit/c3ff73fa2cec530a8595d09e3315555e74fbd0ae

https://sepolia.hop.exchange/
