### ISSUE TITLE
Update FE to be able to support new chains and tokens with minimal effort

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#522]
The high level flow to add new chains and tokens right now is to update the relevant metadata in `core` and to update an env var when building the FE. There are also smaller changes needed within each package to handle case-specific scenarios.

Ideally, these case-specific scenarios can be abstracted away so the addition of new chains and tokens is as simple as updating `core` and an env var. This may require a consolidated config file or a chain-specific class to handle some of the quirky stuff that comes along with each chain.

**Comment by miguelmota** [comment]
Resolved with https://github.com/hop-protocol/hop/commit/3658b2f7c4b0fd6e7b44d595225821cc3d3d3eb2
