### ISSUE TITLE
Retrieve user balances on all chains

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#525]
The FE should be able to be able to know what a user's balances are for Hop-supported tokens on all Hop-supportedchains. This data should be usable throughout the frontend for whatever UI/UX updates might want it.

The UI/UX that will consume this data can be handled at a later time.

### Goal

* Retrieve a user's balance of Hop-supported tokens from all Hop-supported chains for use on the FE
* Expose the balances through a hook and log them to the console for now
* Output type:

```typescript
type TokenBalanceData = {
    userBalance: BigNumber
    userBalanceUsd: number
}

type UserBalances = {
    [chain: string]: {
        [token: string]: TokenBalanceData
    }
}
```

### Considerations
* The onchain calls might be heavy/slow. If they are, this should not block the user from using the app.
* [Multicall](https://github.com/mds1/multicall) is probably the best way to do this, since that is what most wallets/apps use
* RPC endpoints:
  * Since users can bring any RPC they want to the Hop app, this logic should try to gracefully handle arbitrary errors, since there is no RPC error standardization
  * If it makes sense, possibly ignore the user's RPC endpoint and just use the known, public RPC endpoints. They are still not great (no standard errors, public usage affects performance, etc.), but at least they are consistent.

**Comment by miguelmota** [comment]
Resolved with https://github.com/hop-protocol/hop/commit/1b32c4fbfebf242976866ab134b8ac20dfed15ee
