### ISSUE TITLE
Run  getL2TxHashesInChannel  get error by getL2TxHashesInChannel on sepolia.

### ISSUE THREAD

**Issue by liucan163** [hop-protocol/hop#543]
I attempted to parse the frame_data from the input of a Batcher Transaction, and ultimately retrieved the data using zlib.inflateSync. This process works successfully on the mainnet, but fails to parse the input on the testnet. 
I observed a hard fork on the testnet, which resulted in the inability to use the current logic.

https://github.com/ethereum-optimism/optimism/releases
span batches are on testnet - https://github.com/ethereum-optimism/optimism/blob/develop/specs/span-batches.md

where: 
```javascript
packages/hop-node/src/chains/Chains/optimism/inclusion/AbstractOptimismInclusionService.ts
getL2TxHashesInChannel => parseFrames => decompressChannel
```

**Comment by liucan163** [comment]
```javascript
  const frames = await parseFrames(temps.test)
  let numL1BlocksInChannel = 0
  const l2TxHashes = []
  console.log('frames======', frames)
  const decompressedChannel = await decompressChannel(frames[0].data)
``` 

frames====== [
  {
    channelId: 'cd66e26263873ba6bdbc86d745e9a8c9',
    frameNumber: 0,
    data: <Buffer 78 da da c9 9c cf f8 e1 42 33 5b e7 fd 4d 4c 8f 16 b6 4e 0a e3 74 f0 39 dc a9 bb dc 57 bf e9 d8 86 35 27 0f 87 6a 7e 53 36 73 7f f6 c4 a0 b5 95 3b e7 ... 604 more bytes>,
    isLast: true
  }
]

// decompressChannel()
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
    at processChunkSync (node:zlib:457:12)
    at zlibBufferSync (node:zlib:178:12)
    at Object.syncBufferWrapper [as inflateSync] (node:zlib:792:14)
    at decompressChannel (/Users/liucan_1/Documents/codes/node-projects/temps/sync21.js:136:17)
    at /Users/liucan_1/Documents/codes/node-projects/temps/sync21.js:180:39
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
➜

**Comment by shanefontaine** [comment]
Thanks for the issue @liucan163 . Can you describe what your goal is? That logic might be outdated as it was written for an older Optimism spec.

**Comment by shanefontaine** [comment]
Closed as stale.
