### ISSUE TITLE
FE does not handle the case where the user does not have a balance of the gas token on the source network

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#74]
Our UI does not handle the case where a user tries to send funds from one chain to another but does not have assets to pay for gas (xDai on xDai, etc.). 

There are a few issues I will mention below, but see the attached video for the full flow.

### Issues
1. MM does not allow you to execute the "approval" transaction by disabling the button. This may be a MM specific thing.
2. Sending a transaction produces and "Internal JSON-RPC error". I believe this is unrelated to the account balance.

I have verified that issue (1) above is solved by adding xDai to my account.

### Possible Solution
Check the balance of the user prior to sending any transaction. Verify that they have the funds to perform the transaction and block MM from ever appearing & show something in the UI if they do not have enough funds.

https://user-images.githubusercontent.com/9441295/117226607-d942d680-adc9-11eb-9760-fc5f52737ad3.mov

![Screen Shot 2021-05-05 at 5 27 41 PM](https://user-images.githubusercontent.com/9441295/117227445-aa2d6480-adcb-11eb-9f01-e503291feb5b.png)

![Screen Shot 2021-05-05 at 5 59 04 PM](https://user-images.githubusercontent.com/9441295/117227403-9681fe00-adcb-11eb-99f7-7597ded784bf.png)

**Comment by miguelmota** [comment]
![DeepinScreenshot_select-area_20210810113453](https://user-images.githubusercontent.com/168240/128915841-77fd0b71-44d2-40fe-aaf4-ac7edcaa0895.png)

No longer an issue. Closing.
