### ISSUE TITLE
Convert page "to" balance displays an incorrect balance

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#79]
When converting via the AMM on a L2, the "to" balance does not accurately display the amount one would expect to receive.

It appears to work sometimes, but I believe there is some debouncing or network call issue. I've tried to reproduce this issue twice -- I was able to see the unexpected behavior the first time. Ten minutes later, I was unable to and it worked perfectly. **I think this may simply be that the RPC endpoint is taking a long time to load and we might not be handling the case where the user manually inputs numbers and forces a different RPC call.**

To reporduce:
* Convert -> xDAI / USDC / via Saddle -> From Canonical Bridge To Hop Bridge
* Enter any value for "From"
* Deselect the input field in "From" and Select "To". Update the "To" amount with any value.
* Do the same again with the input
* Observe the value in the opposing input box is unexpected.

Below is an example of an unexpected output. For this particular trade, there should have been ~2,000 hUSDC received. 

<img width="650" alt="Screenshot 2021-05-10 at 13 55 07 (1)" src="https://user-images.githubusercontent.com/9441295/117714397-bfb7db00-b18b-11eb-89d2-942cfbe7b69d.png">

**Comment by miguelmota** [comment]
No longer an issue. Closing.
