### ISSUE TITLE
Convert page via AMM seems to use incorrect rates where 

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#88]
When converting via the AMM, I would expect the rates going hUSDC <> USDC to be different if the AMM is not perfectly even. I see this is not the case.

In the images below, I show the same `input` amount for each swap type (hUSDC -> USDC & USDC -> hUSDC). The `output` amount is identical. The right side of the images show that the pool for xDai.USDC & xDai.hUSDC is not perfectly even, so I would expect these `output` amounts to not match either.

Potentially related, in this same setup, when you go from Hop bridge -> Canonical bridge, it asks you to approve "USDC" not "hUSDC". Maybe this page has a bug where only the canonical representation is used on the input?

Edit: When converting from Hop Bridge -> Canonical Bridge, you `approve` the canonical token, which I believe is incorrect. I believe it should `approve` the h token.

<img width="1821" alt="Screen Shot 2021-05-27 at 2 42 00 PM" src="https://user-images.githubusercontent.com/9441295/119900770-d2574180-bef9-11eb-9b95-2e29c046ac3d.png">
<img width="1725" alt="Screen Shot 2021-05-27 at 2 41 50 PM" src="https://user-images.githubusercontent.com/9441295/119900776-d4210500-bef9-11eb-85bb-62c8f15d6713.png">

**Comment by miguelmota** [comment]
No longer an issue. Closing.
